# Generated by Django 4.2.7 on 2026-08-14 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_type', models.CharField(choices=[('heart_rate', 'Heart Rate'), ('blood_pressure', 'Blood Pressure'), ('temperature', 'Temperature'), ('oxygen_saturation', 'Oxygen Saturation'), ('blood_glucose', 'Blood Glucose'), ('weight', 'Weight'), ('ecg', 'ECG Data')], max_length=50)),
                ('value', models.JSONField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_type', models.CharField(choices=[('heart_rate', 'Heart Rate'), ('blood_pressure', 'Blood Pressure'), ('temperature', 'Temperature'), ('oxygen_saturation', 'Oxygen Saturation'), ('blood_glucose', 'Blood Glucose'), ('weight', 'Weight'), ('ecg', 'ECG Data')], max_length=50)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'vital_type')},
            },
        ),
    ]
