# Generated by Django 4.2.7 on 2026-08-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='scenario_id',
            field=models.CharField(blank=True, help_text='Set when a reading was produced by the demo scenario runner', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='source',
            field=models.CharField(choices=[('simulated', 'Simulated'), ('device', 'Device'), ('manual', 'Manual Entry')], default='device', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['user', 'vital_type', '-timestamp'], name='vitals_vita_user_id_dc7135_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsign',
            index=models.Index(fields=['user', 'source'], name='vitals_vita_user_id_33dadb_idx'),
        ),
    ]
