# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('health_risk', 'Health Risk'), ('heart_disease', 'Heart Disease'), ('abnormal_vital', 'Abnormal Vital Sign'), ('fall_risk', 'Fall Risk')], max_length=50)),
                ('input_data', models.JSONField()),
                ('result', models.JSONField()),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'prediction_type'], name='ml_api_pred_user_id_d63791_idx'),
                    models.Index(fields=['created_at'], name='ml_api_pred_created_10aef8_idx'),
                ],
            },
        ),
    ]
